using Common.Attributes;
using Common.Models;
using EFCoreAuditingDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EFCoreAuditingDemo.Data
{
    public class AuditLogDbContext : DbContext
    {
        private readonly string CurrentUserId = Guid.NewGuid().ToString();


        public DbSet<Product> Products { get; set; }
        public DbSet<Audit> Audits { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql("Host=127.0.0.1;Database=EFCoreAuditingDemoDB;Username=postgres;Password=Zevit2019!");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //modelBuilder.ApplyConfigurationsFromAssembly(typeof(AuditLogDbContext).Assembly);
            //modelBuilder.HasPostgresExtension("uuid-ossp");
            base.OnModelCreating(modelBuilder);
        }


        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            var auditEntries = OnBeforeSaveChanges();

            var result = await base.SaveChangesAsync(cancellationToken);

            await OnAfterSaveChangesAsync(auditEntries);

            return result;
        }


        private List<AuditEntry> OnBeforeSaveChanges()
        {
            ChangeTracker.DetectChanges();

            var auditEntries = new List<AuditEntry>();

            foreach (EntityEntry entry in ChangeTracker.Entries<IAuditable>().ToList())
            {
                if (entry.Entity is Audit || entry.State == EntityState.Detached ||
                    entry.State == EntityState.Unchanged)
                    continue;

                var auditEntry = new AuditEntry(entry)
                {
                    AuditType = ConvertTo(entry.State),
                    StateName = entry.State.ToString(),
                    ModifiedBy = CurrentUserId
                };

                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties.Where(property =>
                                                    !Attribute.IsDefined(property.Metadata.PropertyInfo, typeof(AuditIgnore))))
                {
                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }

                    var propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;

                        case EntityState.Modified:
                            if (property.IsModified)
                            {
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;

                        case EntityState.Deleted:
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;
                        case EntityState.Detached:
                        case EntityState.Unchanged:
                        default:
                            break;
                    }
                }
            }

            // Save audit entities that have all the modifications
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                Audits.Add(auditEntry.ToAudit());
            }

            // keep a list of entries where the value of some properties are unknown at this step
            return auditEntries
                .Where(_ => _.HasTemporaryProperties)
                .ToList();
        }

        private Task OnAfterSaveChangesAsync(IReadOnlyCollection<AuditEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
                return Task.CompletedTask;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                Audits.Add(auditEntry.ToAudit());
            }

            return base.SaveChangesAsync();
        }

        static AuditType ConvertTo(EntityState theirGender)
        {
            AuditType auditType;
            switch (theirGender)
            {
                case EntityState.Added:
                    auditType = AuditType.Added;
                    break;
                case EntityState.Modified:
                    auditType = AuditType.Modified;
                    break;
                case EntityState.Deleted:
                    auditType = AuditType.Deleted;
                    break;
                case EntityState.Unchanged:
                    auditType = AuditType.Unchanged;
                    break;
                case EntityState.Detached:
                    auditType = AuditType.Detached;
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }

            return auditType;
        }

    }
}
